M48
; DRILL file {KiCad 9.0.5} date 2025-10-16T21:30:31-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-16T21:30:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.300
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X151.5Y-106.0
T2
X147.92Y-98.0
X150.46Y-98.0
X153.0Y-98.0
M30
