M48
; DRILL file {KiCad 7.0.1-0} date 2024 February 20, Tuesday 17:42:57
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-20T17:42:57-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X151.13Y-50.165
X151.13Y-100.965
X179.705Y-50.165
X179.705Y-100.965
T0
M30
